### ISSUE TITLE
Sprites Too Bright?

### ISSUE THREAD

**Issue by Andrettin** [christopho/solarus-alttp-pack#9]
The sprites seem to uniformly have higher brightness than the original sprites from ALttP. Here is an example of the ALttP sprites available elsewhere:

https://www.spriters-resource.com/resources/sheets/7/7586.png

And here is how many of those sprites look in the pack:
https://raw.githubusercontent.com/solarus-games/solarus-alttp-pack/master/data/sprites/npc/alttp.png

Is this intentional?

**Comment by christopho** [comment]
Yes this is intentional, they have the european palette. In the dev branch there are GIMP scripts to convert colors: https://github.com/solarus-games/solarus-alttp-pack/tree/dev/tools

**Comment by Andrettin** [comment]
Thanks for the explanation :) I didn't know know the European version of ALttP had a different palette.

Keep up the great work!
